import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  vi: {
    // Nav
    home: 'Trang chủ',
    jobs: 'Việc làm',
    companies: 'Công ty',
    blog: 'Blog',
    about: 'Giới thiệu',
    contact: 'Liên hệ',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    profile: 'Hồ sơ',
    logout: 'Đăng xuất',
    notifications: 'Thông báo',
    messages: 'Tin nhắn',
    dashboard: 'Bảng điều khiển',
    myProfile: 'Hồ sơ của tôi',
    myApplications: 'Đơn ứng tuyển của tôi',
    savedJobs: 'Công việc yêu thích',
    settings: 'Cài đặt',
    companyProfile: 'Hồ sơ công ty',
    manageJobs: 'Quản lý tin đăng',
    users: 'Người dùng',

    // Hero
    heroBadge: 'Nền tảng tuyển dụng #1 Việt Nam',
    heroTitlePart1: 'Kết nối tài năng với',
    heroTitlePart2: 'Cơ hội tương lai',
    heroSubTitle: 'Tìm kiếm hàng ngàn việc làm từ các công ty hàng đầu. Khởi đầu sự nghiệp mơ ước của bạn ngay hôm nay với SchneeJob.',
    heroSearchPlaceholder: 'Tên công việc, kỹ năng hoặc công ty...',
    heroSearchButton: 'Tìm việc ngay',
    trustedBy: 'Được tin dùng bởi',

    // Stats
    statsJobs: 'Việc làm đang tuyển',
    statsCompanies: 'Công ty đối tác',
    statsCandidates: 'Ứng viên tiềm năng',
    statPlacements: 'Lượt kết nối thành công',

    // Features / Categories
    popularCategories: 'Danh mục phổ biến',
    viewAllJobs: 'Xem tất cả việc làm',
    itSoftware: 'Công nghệ thông tin',
    marketing: 'Marketing',
    design: 'Thiết kế đồ họa',
    finance: 'Tài chính - Ngân hàng',
    sales: 'Kinh doanh - Bán hàng',
    humanResources: 'Nhân sự',

    // Promo Banner
    promoBadge: 'Dành cho nhà tuyển dụng',
    promoTitle: 'Tuyển dụng nhân tài đột phá cùng SchneeJob',
    promoSubTitle: 'Giải pháp tuyển dụng thông minh giúp bạn tìm kiếm và kết nối với những ứng viên xuất sắc nhất một cách nhanh chóng.',
    promoStartButton: 'Bắt đầu ngay',
    promoLearnMore: 'Tìm hiểu thêm',
    featSpeedTitle: 'Tốc độ',
    featSpeedDesc: 'Đăng tin và nhận hồ sơ chỉ trong vài phút',
    featSecurityTitle: 'Bảo mật',
    featSecurityDesc: 'Thông tin doanh nghiệp luôn được bảo vệ',
    featConnectTitle: 'Kết nối',
    featConnectDesc: 'Hệ thống gợi ý ứng viên thông minh AI',
    featReputationTitle: 'Uy tín',
    featReputationDesc: 'Cộng đồng tuyển dụng lớn nhất Việt Nam',

    // Common
    loading: 'Đang tải...',
    search: 'Tìm kiếm',
    location: 'Địa điểm',
    category: 'Danh mục',
    salary: 'Mức lương',
    applyNow: 'Ứng tuyển ngay',
    saveJob: 'Lưu việc làm',
    share: 'Chia sẻ',
    recommendedJobs: 'Việc làm gợi ý',
    hotJobs: 'Việc làm hot',
    discover: 'Khám phá',
    topIndustries: 'Ngành nổi bật',
    recruitmentFeed: 'Bảng tin tuyển dụng',
    newest: 'Mới nhất',
    mostPopular: 'Phổ biến nhất',
    noPostsYet: 'Chưa có bài viết nào',
    noPostsYetDesc: 'Các công ty sẽ sớm chia sẻ thông tin tuyển dụng tại đây',
    suggestedJobs: 'Việc làm gợi ý',
    topCompanies: 'Công ty hàng đầu',
    viewMore: 'Xem thêm',
    viewAll: 'Xem tất cả',

    // Jobs Page
    jobSearchPlaceholder: 'Tìm kiếm công việc, kỹ năng...',
    advancedFilter: 'Bộ lọc nâng cao',
    allLocations: 'Tất cả địa điểm',
    level: 'Cấp bậc',
    type: 'Loại hình',
    workMode: 'Hình thức',
    salaryRangeLabel: 'Mức lương (Triệu)',
    popularSkills: 'Kỹ năng phổ biến',
    clearFilters: 'Xóa bộ lọc',
    foundJobs: 'Tìm thấy {count} công việc',
    noJobsFound: 'Không tìm thấy việc làm',
    noJobsFoundDesc: 'Hãy thử tìm các từ khóa khác hoặc điều chỉnh bộ lọc của bạn',
    loadMore: 'Xem thêm việc làm',
    jobExpired: 'Hết hạn nộp hồ sơ',
    jobClosed: 'Đã đóng tuyển dụng',
    applicationDeadlinePassed: 'Hạn nộp hồ sơ cho công việc này đã qua.',
    jobNoLongerAccepting: 'Công việc này không còn nhận hồ sơ ứng tuyển.',
    jobUnavailable: 'Việc làm không khả dụng',
    sortByLabel: 'Sắp xếp: {label}',
    sortDefault: 'Mặc định',
    sortNewest: 'Mới nhất',
    sortSalaryHigh: 'Lương cao nhất',
    all: 'Tất cả',

    // Companies Page
    companySearchPlaceholder: 'Tìm tên công ty...',
    topEmployer: 'Nhà tuyển dụng hàng đầu',
    companySize: 'Quy môi công ty',
    foundCompanies: 'Tìm thấy {count} công ty',
    noCompaniesFound: 'Không tìm thấy công ty nào',
    noCompaniesFoundDesc: 'Hãy thử thay đổi tiêu chí tìm kiếm của bạn',
    companyHeaderTitle1: 'Khám phá',
    companyHeaderTitle2: 'Văn hóa Doanh nghiệp',
    companyHeaderSubTitle: 'Tìm hiểu môi trường làm việc, phúc lợi và cơ hội nghề nghiệp tại các công ty công nghệ hàng đầu Việt Nam.',
    industry: 'Ngành nghề',
    matchingCompanies: 'Công ty phù hợp',

    // Auth Pages
    loginTitle: 'Đăng nhập',
    loginSubTitle: 'Chào mừng trở lại! Vui lòng đăng nhập để tiếp tục.',
    registerTitle: 'Đăng ký tài khoản',
    registerSubTitle: 'Tham gia cùng hàng ngàn ứng viên và nhà tuyển dụng ngay hôm nay.',
    emailLabel: 'Email',
    passwordLabel: 'Mật khẩu',
    rememberMe: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    noAccount: 'Chưa có tài khoản?',
    alreadyHaveAccount: 'Đã có tài khoản?',
    registerNow: 'Đăng ký ngay',
    loginNow: 'Đăng nhập ngay',
    loginWithGoogle: 'Đăng nhập với Google',
    loginWithFacebook: 'Đăng nhập với Facebook',
    loginSuccess: 'Đăng nhập thành công!',
    loginFailed: 'Đăng nhập thất bại. Vui lòng kiểm tra tài khoản và mật khẩu.',
    loggingIn: 'Đang đăng nhập...',
    demoAccount: 'Tài khoản demo:',
    clickToFill: 'Click để điền',
    fullNameLabel: 'Họ và tên',
    phoneNumberLabel: 'Số điện thoại',
    confirmPasswordLabel: 'Xác nhận mật khẩu',
    agreeTermsPart1: 'Tôi đồng ý với',
    agreeTermsPart2: 'và',
    registerSuccessJobseeker: 'Đăng ký thành công! Vui lòng đăng nhập.',
    registerSuccessEmployer: 'Đăng ký thành công! Vui lòng điền thông tin công ty.',
    jobseekerRole: 'Người tìm việc',
    employerRole: 'Nhà tuyển dụng',
    jobseekerDesc: 'Tìm việc làm phù hợp',
    employerDesc: 'Đăng tin tuyển dụng',
    authenticating: 'Đang xác thực...',
    registering: 'Đang đăng ký...',

    // Footer
    footerDesc: 'SchneeJob - Nền tảng tuyển dụng và tìm việc làm hàng đầu Việt Nam. Kết nối ứng viên với cơ hội việc làm phù hợp nhất.',
    footerJobSeekers: 'Người tìm việc',
    footerEmployers: 'Nhà tuyển dụng',
    footerAbout: 'Về chúng tôi',
    footerLegal: 'Pháp lý',
    findJobs: 'Tìm việc làm',
    companyList: 'Danh sách công ty',
    createCV: 'Tạo CV online',
    careerAdvice: 'Tư vấn nghề nghiệp',
    postJobNow: 'Đăng tin tuyển dụng',
    pricing: 'Bảng giá dịch vụ',
    searchCV: 'Tìm kiếm CV',
    recruitmentSolutions: 'Giải pháp tuyển dụng',
    contactUs: 'Liên hệ',
    blog: 'Blog',
    faq: 'FAQ',
    privacyPolicy: 'Chính sách bảo mật',
    termsOfService: 'Điều khoản sử dụng',
    cookiePolicy: 'Chính sách Cookie',
    allRightsReserved: 'Bản quyền thuộc về',
    followUs: 'Theo dõi chúng tôi'
  },
  en: {
    // Nav
    home: 'Home',
    jobs: 'Jobs',
    companies: 'Companies',
    blog: 'Blog',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    profile: 'Profile',
    logout: 'Logout',
    notifications: 'Notifications',
    messages: 'Messages',
    dashboard: 'Dashboard',
    myProfile: 'My Profile',
    myApplications: 'My Applications',
    savedJobs: 'Saved Jobs',
    settings: 'Settings',
    companyProfile: 'Company Profile',
    manageJobs: 'Manage Jobs',
    users: 'Users',

    // Hero
    heroBadge: '#1 Recruitment Platform in Vietnam',
    heroTitlePart1: 'Connect Talent with',
    heroTitlePart2: 'Future Opportunities',
    heroSubTitle: 'Search thousands of jobs from top companies. Start your dream career today with SchneeJob.',
    heroSearchPlaceholder: 'Job title, skills or company...',
    heroSearchButton: 'Find Jobs Now',
    trustedBy: 'Trusted by',

    // Stats
    statsJobs: 'Active Jobs',
    statsCompanies: 'Partner Companies',
    statsCandidates: 'Potential Candidates',
    statPlacements: 'Successful Placements',

    // Features / Categories
    popularCategories: 'Popular Categories',
    viewAllJobs: 'View All Jobs',
    itSoftware: 'IT - Software',
    marketing: 'Marketing',
    design: 'Graphic Design',
    finance: 'Finance - Banking',
    sales: 'Sales',
    humanResources: 'Human Resources',

    // Promo Banner
    promoBadge: 'For Employers',
    promoTitle: 'Scale Your Team with SchneeJob',
    promoSubTitle: 'Smart recruitment solutions to help you find and connect with top talent quickly.',
    promoStartButton: 'Get Started',
    promoLearnMore: 'Learn More',
    featSpeedTitle: 'Speed',
    featSpeedDesc: 'Post jobs and receive applications in minutes',
    featSecurityTitle: 'Security',
    featSecurityDesc: 'Company information is always protected',
    featConnectTitle: 'Connection',
    featConnectDesc: 'AI-driven candidate recommendation system',
    featReputationTitle: 'Reputation',
    featReputationDesc: 'Largest recruitment community in Vietnam',

    // Common
    loading: 'Loading...',
    search: 'Search',
    location: 'Location',
    category: 'Category',
    salary: 'Salary',
    applyNow: 'Apply Now',
    saveJob: 'Save Job',
    share: 'Share',
    recommendedJobs: 'Recommended Jobs',
    hotJobs: 'Hot Jobs',
    discover: 'Discover',
    topIndustries: 'Top Industries',
    recruitmentFeed: 'Recruitment Feed',
    newest: 'Newest',
    mostPopular: 'Most Popular',
    noPostsYet: 'No posts yet',
    noPostsYetDesc: 'Companies will share recruitment information here soon',
    suggestedJobs: 'Suggested Jobs',
    topCompanies: 'Top Companies',
    viewMore: 'View more',
    viewAll: 'View all',

    // Jobs Page
    jobSearchPlaceholder: 'Find jobs, skills...',
    advancedFilter: 'Advanced Filters',
    allLocations: 'All Locations',
    level: 'Level',
    type: 'Job Type',
    workMode: 'Work Mode',
    salaryRangeLabel: 'Salary Range (Million)',
    popularSkills: 'Popular Skills',
    clearFilters: 'Clear Filters',
    foundJobs: 'Found {count} jobs',
    noJobsFound: 'No jobs found',
    noJobsFoundDesc: 'Try different keywords or adjust your filters',
    loadMore: 'Load more jobs',
    jobExpired: 'Application Deadline Passed',
    jobClosed: 'Job Closed',
    applicationDeadlinePassed: 'The application deadline for this job has passed.',
    jobNoLongerAccepting: 'This job is no longer accepting applications.',
    jobUnavailable: 'Job Unavailable',
    sortByLabel: 'Sort by: {label}',
    sortDefault: 'Default',
    sortNewest: 'Newest',
    sortSalaryHigh: 'Highest Salary',
    all: 'All',

    // Companies Page
    companySearchPlaceholder: 'Find company names...',
    topEmployer: 'Top Employers',
    companySize: 'Company Size',
    foundCompanies: 'Found {count} companies',
    noCompaniesFound: 'No companies found',
    noCompaniesFoundDesc: 'Try changing your search criteria',
    companyHeaderTitle1: 'Explore',
    companyHeaderTitle2: 'Company Culture',
    companyHeaderSubTitle: 'Learn about the work environment, benefits, and career opportunities at top tech companies.',
    industry: 'Industry',
    matchingCompanies: 'Matching companies',

    // Auth Pages
    loginTitle: 'Login',
    loginSubTitle: 'Welcome back! Please login to continue.',
    registerTitle: 'Register Account',
    registerSubTitle: 'Join thousands of candidates and employers today.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    registerNow: 'Register now',
    loginNow: 'Login now',
    loginWithGoogle: 'Login with Google',
    loginWithFacebook: 'Login with Facebook',
    loginSuccess: 'Login successful!',
    loginFailed: 'Login failed. Please check your email and password.',
    loggingIn: 'Logging in...',
    demoAccount: 'Demo accounts:',
    clickToFill: 'Click to fill',
    fullNameLabel: 'Full Name',
    phoneNumberLabel: 'Phone Number',
    confirmPasswordLabel: 'Confirm Password',
    agreeTermsPart1: 'I agree to the',
    agreeTermsPart2: 'and',
    registerSuccessJobseeker: 'Registration successful! Please login.',
    registerSuccessEmployer: 'Registration successful! Please fill in company info.',
    jobseekerRole: 'Job Seeker',
    employerRole: 'Employer',
    jobseekerDesc: 'Find suitable jobs',
    employerDesc: 'Post job recruitment',
    authenticating: 'Authenticating...',
    registering: 'Registering...',

    // Footer
    footerDesc: 'SchneeJob - Vietnam\'s leading recruitment and job search platform. Connecting candidates with the best job opportunities.',
    footerJobSeekers: 'Job Seekers',
    footerEmployers: 'Employers',
    footerAbout: 'About Us',
    footerLegal: 'Legal',
    findJobs: 'Find Jobs',
    companyList: 'Company List',
    createCV: 'Online CV Builder',
    careerAdvice: 'Career Advice',
    postJobNow: 'Post a Job',
    pricing: 'Pricing Plans',
    searchCV: 'Search CVs',
    recruitmentSolutions: 'Recruitment Solutions',
    contactUs: 'Contact Us',
    blog: 'Blog',
    faq: 'FAQ',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    allRightsReserved: 'All rights reserved',
    followUs: 'Follow Us'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('schneejob_language') || 'vi');

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('schneejob_language', lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
